package com.mycompany.chat.pubsub.view;

import com.mycompany.chat.pubsub.client.ClienteConexao;
import com.mycompany.chat.pubsub.security.CryptoUtil;
import java.security.PublicKey;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import org.json.simple.JSONArray;
import org.json.simple.JSONObject;
import org.json.simple.parser.JSONParser;

/**
 *
 * @author Carol
 */
public class TelaChat extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(TelaChat.class.getName());

    /**
     * Creates new form TelaChat
     */
    private ClienteConexao cliente;
    private DefaultListModel<String> modeloTopicos;
    private String topicoAberto = null;
    private final Map<String, Integer> notificacoesPorTopico = new HashMap<>();
    private final List<String> topicosReais = new ArrayList<>();
    private DefaultListModel<String> modeloParticipante;
    private DefaultListModel<String> modeloSolicitacoes;

    private final Map<String, List<String>> mensagensPorTopico = new HashMap<>();

    public TelaChat(ClienteConexao cliente) {
        initComponents();

        modeloParticipante = new DefaultListModel<>();
        listParticipantes.setModel(modeloParticipante);
        this.cliente = cliente;

        lblBemVindo.setText("Bem vindo(a) " + cliente.getUsuarioAtual() + "!");

        jScrollPane2.setVisible(false);
        txtMensagem.setVisible(false);
        btnEnviar.setVisible(false);
        btnVoltar.setVisible(false);
        lblTopicoAtual.setVisible(false);
        btnSairTopico.setVisible(false);
        listParticipantes.setVisible(false);
        lblParticipantes.setVisible(false);
        lblSolicitacoes.setVisible(false);
        btnAprovar.setVisible(false);
        btnRecusar.setVisible(false);

        modeloTopicos = new DefaultListModel<>();
        listaTopicos.setModel(modeloTopicos);

        modeloSolicitacoes = new DefaultListModel<>();
        listSolicitacoes.setModel(modeloSolicitacoes);

        configurarRecebimento();

        cliente.solicitarTopicos();
        cliente.sincronizarMensagensPendentes();

        setLocationRelativeTo(null);

    }

    public TelaChat() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTopico = new javax.swing.JLabel();
        btnCriarTopico = new javax.swing.JButton();
        btnEntrarTopico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        areaMensagens = new javax.swing.JTextArea();
        txtMensagem = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomeTopico = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        listaTopicos = new javax.swing.JList<>();
        btnUsarTopico = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblParticipantes = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        btnSairTopico = new javax.swing.JButton();
        lblTopicoAtual = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        listParticipantes = new javax.swing.JList<>();
        lblTopicosDisponiveis = new javax.swing.JLabel();
        lblBemVindo = new javax.swing.JLabel();
        lblSolicitacoes = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        listSolicitacoes = new javax.swing.JList<>();
        btnAprovar = new javax.swing.JButton();
        btnRecusar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTopico.setText("Nome");

        btnCriarTopico.setText("Criar tópico");
        btnCriarTopico.addActionListener(this::btnCriarTopicoActionPerformed);

        btnEntrarTopico.setText("Enviar solicitação");
        btnEntrarTopico.addActionListener(this::btnEntrarTopicoActionPerformed);

        areaMensagens.setColumns(20);
        areaMensagens.setRows(5);
        jScrollPane1.setViewportView(areaMensagens);

        jScrollPane2.setViewportView(jScrollPane1);

        txtMensagem.addActionListener(this::txtMensagemActionPerformed);

        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(this::btnEnviarActionPerformed);

        nomeTopico.addActionListener(this::nomeTopicoActionPerformed);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(nomeTopico, javax.swing.GroupLayout.DEFAULT_SIZE, 194, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(nomeTopico, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        listaTopicos.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(listaTopicos);

        btnUsarTopico.setText("Usar Tópico");
        btnUsarTopico.addActionListener(this::btnUsarTopicoActionPerformed);

        btnSair.setText("Desconectar");
        btnSair.addActionListener(this::btnSairActionPerformed);

        lblParticipantes.setText("Participantes");

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(this::btnVoltarActionPerformed);

        btnSairTopico.setText("Sair");
        btnSairTopico.addActionListener(this::btnSairTopicoActionPerformed);

        lblTopicoAtual.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblTopicoAtual.setText("Topico Atual");
        lblTopicoAtual.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
                lblTopicoAtualAncestorRemoved(evt);
            }
        });

        listParticipantes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane4.setViewportView(listParticipantes);

        lblTopicosDisponiveis.setText("Topicos Disponíveis");

        lblBemVindo.setFont(new java.awt.Font("Segoe UI Semibold", 1, 18)); // NOI18N
        lblBemVindo.setText("Bem vindo");

        lblSolicitacoes.setText("Solicitações");

        listSolicitacoes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane5.setViewportView(listSolicitacoes);

        btnAprovar.setText("Aprovar");
        btnAprovar.addActionListener(this::btnAprovarActionPerformed);

        btnRecusar.setText("Recusar");
        btnRecusar.addActionListener(this::btnRecusarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3)
                    .addComponent(btnUsarTopico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnEntrarTopico)
                            .addComponent(btnVoltar)
                            .addComponent(btnSairTopico))
                        .addGap(0, 33, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblTopicosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(281, 281, 281)
                                .addComponent(btnEnviar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblBemVindo)
                                .addGap(71, 71, 71)
                                .addComponent(btnSair))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addComponent(txtMensagem)
                                .addGap(90, 90, 90)))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTopico)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCriarTopico))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addComponent(lblTopicoAtual)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSolicitacoes)
                        .addGap(38, 38, 38))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblParticipantes, javax.swing.GroupLayout.DEFAULT_SIZE, 147, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnRecusar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(btnAprovar, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSair)
                            .addComponent(btnVoltar))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblBemVindo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnCriarTopico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblParticipantes)
                            .addComponent(lblTopicoAtual)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTopico)
                            .addComponent(btnSairTopico))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTopicosDisponiveis, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 342, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUsarTopico))
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblSolicitacoes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnAprovar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtMensagem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEnviar)
                    .addComponent(btnEntrarTopico)
                    .addComponent(btnRecusar))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCriarTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCriarTopicoActionPerformed
        String topico = nomeTopico.getText().trim();

        if (topico.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite o nome do topico");
            return;
        }

        cliente.criarTopico(topico);

        nomeTopico.setText("");
    }//GEN-LAST:event_btnCriarTopicoActionPerformed

    private void btnEntrarTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarTopicoActionPerformed
        String topico = getTopicoSelecionado();

        if (topico == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um topico da lista.");
            return;
        }

        cliente.entrarTopico(topico);
    }//GEN-LAST:event_btnEntrarTopicoActionPerformed

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String mensagem = txtMensagem.getText().trim();
        if (mensagem.isEmpty()) {
            return;
        }
        if (topicoAberto == null) {
            JOptionPane.showMessageDialog(this, "Abra um topico antes de enviar mensagens.");
            return;
        }
        if (!cliente.possuiChaveTopico(topicoAberto)) {
            JOptionPane.showMessageDialog(this, "vc nao tem chave do topico");
            return;
        }
        try {
            String chaveTopico = cliente.getChaveTopico(topicoAberto);
            Integer versao = cliente.getVersaoChaveTopico(chaveTopico);
            String mensagemCriptografada = CryptoUtil.criptografarAES(mensagem, chaveTopico);

            cliente.enviarMensagemCriptografada(mensagemCriptografada, versao);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "erro p criptografar");
            e.printStackTrace();
        }

        System.out.println("Topico aberto: " + topicoAberto);
        System.out.println("Possui chave? " + cliente.possuiChaveTopico(topicoAberto));
        System.out.println("Chave: " + cliente.getChaveTopico(topicoAberto));
        System.out.println("Versao: " + cliente.getVersaoChaveTopico(topicoAberto));
        txtMensagem.setText(" ");
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtMensagemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMensagemActionPerformed
        btnEnviarActionPerformed(evt);
    }//GEN-LAST:event_txtMensagemActionPerformed

    private void btnUsarTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUsarTopicoActionPerformed
        String topico = getTopicoSelecionado();
        if (topico == null) {
            javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Selecione um tópico na lista."
            );
            return;
        }

        cliente.usarTopicos(topico);
    }//GEN-LAST:event_btnUsarTopicoActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        cliente.desconectar();
        TelaLogin login = new TelaLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        topicoAberto = null;

        jScrollPane2.setVisible(false);
        txtMensagem.setVisible(false);
        btnEnviar.setVisible(false);
        btnVoltar.setVisible(false);
        lblTopicoAtual.setVisible(false);
        btnSairTopico.setVisible(false);
        btnSair.setVisible(true);
        lblParticipantes.setVisible(false);
        listParticipantes.setVisible(false);
        lblSolicitacoes.setVisible(false);
        btnAprovar.setVisible(false);
        btnRecusar.setVisible(false);
        lblTopico.setVisible(true);
        btnCriarTopico.setVisible(true);
        nomeTopico.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnSairTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairTopicoActionPerformed
        String topico = getTopicoSelecionado();

        if (topico == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Selecione um topico para sair.");
            return;
        }

        int opcao = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "Deseja sair do tópico \"" + topico + "\"?",
                "Confirmar saída",
                javax.swing.JOptionPane.YES_NO_OPTION
        );

        if (opcao != javax.swing.JOptionPane.YES_OPTION) {
            return;
        }

        cliente.sairTopico(topico);

        if (topico.equals(topicoAberto)) {
            topicoAberto = null;

            jScrollPane2.setVisible(false);
            txtMensagem.setVisible(false);
            btnEnviar.setVisible(false);
            btnVoltar.setVisible(false);
            lblTopicoAtual.setVisible(false);
            btnSairTopico.setVisible(false);
            btnSair.setVisible(true);
            lblParticipantes.setVisible(false);
            listParticipantes.setVisible(false);
        }
    }//GEN-LAST:event_btnSairTopicoActionPerformed

    private void nomeTopicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTopicoActionPerformed
        btnCriarTopicoActionPerformed(evt);
    }//GEN-LAST:event_nomeTopicoActionPerformed

    private void lblTopicoAtualAncestorRemoved(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblTopicoAtualAncestorRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_lblTopicoAtualAncestorRemoved

    private void btnAprovarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAprovarActionPerformed
        String usuario = listSolicitacoes.getSelectedValue();

        if (usuario == null || usuario.equals("Nenhuma solicitacao")) {
            JOptionPane.showMessageDialog(this, "Selecione uma solicitacao");
            return;
        }

        if (topicoAberto == null) {
            JOptionPane.showMessageDialog(this, "Nenhum topico aberto");
            return;
        }

        cliente.aprovarEntrada(topicoAberto, usuario);
    }//GEN-LAST:event_btnAprovarActionPerformed

    private void btnRecusarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRecusarActionPerformed
        String usuario = listSolicitacoes.getSelectedValue();

        if (usuario == null || usuario.equals("Nenhuma solicitacao")) {
            JOptionPane.showMessageDialog(this, "Selecione uma solicitacao");
            return;
        }

        if (topicoAberto == null) {
            JOptionPane.showMessageDialog(this, "Nenhum topico aberto");
            return;
        }

        cliente.recusarEntrada(topicoAberto, usuario);
    }//GEN-LAST:event_btnRecusarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new TelaChat().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaMensagens;
    private javax.swing.JButton btnAprovar;
    private javax.swing.JButton btnCriarTopico;
    private javax.swing.JButton btnEntrarTopico;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnRecusar;
    private javax.swing.JButton btnSair;
    private javax.swing.JButton btnSairTopico;
    private javax.swing.JButton btnUsarTopico;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel lblBemVindo;
    private javax.swing.JLabel lblParticipantes;
    private javax.swing.JLabel lblSolicitacoes;
    private javax.swing.JLabel lblTopico;
    private javax.swing.JLabel lblTopicoAtual;
    private javax.swing.JLabel lblTopicosDisponiveis;
    private javax.swing.JList<String> listParticipantes;
    private javax.swing.JList<String> listSolicitacoes;
    private javax.swing.JList<String> listaTopicos;
    private javax.swing.JTextField nomeTopico;
    private javax.swing.JTextField txtMensagem;
    // End of variables declaration//GEN-END:variables

    private void configurarRecebimento() {
        cliente.setMensagemListener(mensagem -> {
            SwingUtilities.invokeLater(() -> {
                try {
                    System.out.println("RECEBIDO NA TELA: " + mensagem);

                    JSONParser parser = new JSONParser();
                    JSONObject json = (JSONObject) parser.parse(mensagem);
                    String tipo = (String) json.get("type");

                    System.out.println("TIPO RECEBIDO: " + tipo);

                    if ("TOPIC_LIST".equals(tipo)) {
                        atualizarListaTopicos(json);
                        return;
                    }

                    if ("PARTICIPANT_LIST".equals(tipo)) {
                        atualizarListaParticipantes(json);
                        return;
                    }

                    if ("ACCESS_REQUEST_LIST".equals(tipo)) {
                        atulizarListaSolicitacoes(json);
                        return;
                    }

                    if ("MESSAGE_HISTORY".equals(tipo)) {
                        exibirHistoricoMensagens(json);
                        return;
                    }

                    if ("MESSAGE".equals(tipo)) {
                        processaMensagemRecebida(json);
                        return;
                    }

                    if ("SEND_TOPIC_KEY_REQUEST".equals(tipo)) {
                        processarPedidoEnvio(json);
                    }

                    if ("TOPIC_KEY_PACKAGE".equals(tipo)) {
                        processarPacoteChaveTopico(json);
                        return;
                    }
                    areaMensagens.append(cliente.formatarMensagem(mensagem) + "\n");
                } catch (org.json.simple.parser.ParseException e) {
                    tratarMensagem(mensagem);
                } catch (Exception e) {
                    System.out.println("ERRO AO PROCESSAR MENSAGEM NA TELA");
                    e.printStackTrace();
                    areaMensagens.append(mensagem + "\n");
                }
            });
        });
    }

    private void abrirAreaMensagens(String topico) {
        topicoAberto = topico;

        notificacoesPorTopico.put(topico, 0);
        atualizarListaTopicoVisual();

        lblTopicoAtual.setText("Topico: " + topico);

        jScrollPane2.setVisible(true);
        txtMensagem.setVisible(true);
        btnEnviar.setVisible(true);
        btnVoltar.setVisible(true);
        lblTopicoAtual.setVisible(true);
        btnSairTopico.setVisible(true);
        lblSolicitacoes.setVisible(false);
        btnAprovar.setVisible(true);
        btnRecusar.setVisible(true);
        btnSair.setVisible(false);
        lblParticipantes.setVisible(true);
        listParticipantes.setVisible(true);
        lblTopico.setVisible(false);
        btnCriarTopico.setVisible(false);
        nomeTopico.setVisible(false);

        areaMensagens.setText("[SISTEMA] Carregando as mensagens do topico...\n");

        cliente.solicitarParticipantes(topico);
        cliente.solicitarSolicitacoes(topico);
    }

    private void tratarMensagem(String mensagem) {
        if (mensagem.startsWith("Agora voce esta usando o topico:")) {
            String topico = mensagem.replace("Agora voce esta usando o topico: ", "").trim();
            abrirAreaMensagens(topico);
            cliente.baixarMensagens(topico);
            cliente.solicitarParticipantes(topico);

            return;
        }
        areaMensagens.append("[SISTEMA} " + mensagem + "\n");
    }

    private void processaMensagemRecebida(JSONObject json) {
        try {
            String topico = (String) json.get("topic");
            String remetente = (String) json.get("from");
            String mensagem = (String) json.get("message");
            String textoFinal = mensagem;

            if (cliente.possuiChaveTopico(topico)) {
                try {
                    String chaveTopico = cliente.getChaveTopico(topico);
                    textoFinal = CryptoUtil.descriptografarAES(mensagem, chaveTopico);
                } catch (Exception e) {
                    textoFinal = "[Mensagem criptografada - chave inválida ou ausente]";
                }
            } else {
                textoFinal = "[Mensagem criptografada - sem chave do tópico]";
            }

            String textoFormatado = "[" + topico + "] " + remetente + ": " + textoFinal;

            mensagensPorTopico.computeIfAbsent(topico, k -> new ArrayList<>()).add(textoFormatado);

            if (topicoAberto != null && topicoAberto.equals(topico)) {
                areaMensagens.append(textoFormatado + "\n");
                notificacoesPorTopico.put(topico, 0);
            } else {
                int qtdAtual = notificacoesPorTopico.getOrDefault(topico, 0);
                notificacoesPorTopico.put(topico, qtdAtual + 1);
            }

            atualizarListaTopicoVisual();

        } catch (Exception e) {
            areaMensagens.append("[ERRO] Falha ao processar mensagem.\n");
            e.printStackTrace();
        }
    }

    private void exibirHistoricoMensagens(JSONObject json) {
        try {
            JSONArray mensagens = (JSONArray) json.get("messages");
            String topico = (String) json.get("topic");
            System.out.println("EXIBINDO HISTORICO DO TOPICO: " + topico);
            areaMensagens.setText("");
            if (mensagens == null || mensagens.isEmpty()) {
                areaMensagens.append("[SISTEMA] Nenhuma mensagem neste tópico ainda.\n");
                return;
            }
            System.out.println("QUANTIDADE DE MENSAGENS: " + mensagens.size());
            mensagensPorTopico.remove(topico);

            for (Object obj : mensagens) {
                JSONObject msgJson = (JSONObject) obj;
                String topicoMsg = (String) msgJson.get("topic");
                String remetente = (String) msgJson.get("from");
                String conteudo = (String) msgJson.get("message");
                String conteudoFinal = conteudo;
                if (cliente.possuiChaveTopico(topicoMsg)) {
                    try {
                        String chaveTopico = cliente.getChaveTopico(topicoMsg);
                        conteudoFinal = CryptoUtil.descriptografarAES(conteudo, chaveTopico);
                    } catch (Exception e) {
                        conteudoFinal = "[Mensagem criptografada - chave inválida]";
                    }
                } else {
                    conteudoFinal = "[Mensagem criptografada - sem chave do tópico]";
                }
                String textoFormatado
                        = "[" + topicoMsg + "] " + remetente + ": " + conteudoFinal;
                mensagensPorTopico
                        .computeIfAbsent(topicoMsg, k -> new java.util.ArrayList<>())
                        .add(textoFormatado);
                areaMensagens.append(textoFormatado + "\n");
            }
            notificacoesPorTopico.put(topico, 0);
            atualizarListaTopicoVisual();

        } catch (Exception e) {
            System.out.println("ERRO DENTRO DO exibirHistoricoMensagens");
            e.printStackTrace();
        }
    }

    private void processarPedidoEnvio(JSONObject json) {
        try {
            String topico = (String) json.get("topic");
            String usuarioAprovado = (String) json.get("approvedUser");
            String chavePublicaUsuario = (String) json.get("approvedUserPublicKey");

            if (!cliente.possuiChaveTopico(topico)) {
                areaMensagens.append("vc nao possui chave ");
                return;
            }
            String chaveTopico = cliente.getChaveTopico(topico);
            Integer versao = cliente.getVersaoChaveTopico(topico);
            PublicKey chaveUsuario = CryptoUtil.base64ParaChavePublica(chavePublicaUsuario);
            String chaveCriptografada = CryptoUtil.criptografarComChavePublica(chaveTopico, chaveUsuario);
            cliente.enviarPacoteChaveTopico(topico, usuarioAprovado, versao, chaveCriptografada);
            areaMensagens.append("chave enviada para " + usuarioAprovado);
        } catch (Exception e) {
            areaMensagens.append("falha ao enviar chave\n");
            e.printStackTrace();
        }
    }
    
    private void processarPacoteChaveTopico(JSONObject json) {
        try {
            String topico = (String) json.get("topic");
            String remetente = (String) json.get("from");
            String chaveCriptografada = (String) json.get("encryptedKey");

            Long versaoLong = (Long) json.get("keyVersion");
            int versao = versaoLong.intValue();

            String chaveAES = CryptoUtil.descriptografarComChavePrivada(chaveCriptografada, cliente.getChavePrivadaCliente());
            cliente.salvarChaveTopico(topico, chaveAES, versao);
            areaMensagens.append("[SISTEMA] Chave do tópico "
                    + topico
                    + " recebida de "
                    + remetente
                    + ". Versão: "
                    + versao
                    + "\n");
        } catch (Exception e) {
            areaMensagens.append("nao foi possivel abrir a chave do topico");
            e.printStackTrace();
        }
    }
    
    private void atualizarListaTopicos(JSONObject json) {
        JSONArray topicos = (JSONArray) json.get("topics");
        topicosReais.clear();
        for (Object obj : topicos) {
            topicosReais.add(obj.toString());
        }
        atualizarListaTopicoVisual();
    }
    
    private void atualizarListaTopicoVisual() {
        modeloTopicos.clear();

        for (String topico : topicosReais) {
            int qtd = notificacoesPorTopico.getOrDefault(topico, 0);
            if (qtd > 0) {
                modeloTopicos.addElement(topico + " (" + qtd + ")");
            } else {
                modeloTopicos.addElement(topico);
            }
        }
    }    

    private String getTopicoSelecionado() {
        String valor = listaTopicos.getSelectedValue();
        if (valor == null) {
            return null;
        }
        return valor.replaceAll(" \\(\\d+\\)$", "");
    }

    private void atualizarListaParticipantes(JSONObject json) {
        String topico = (String) json.get("topic");
        if (topicoAberto == null || !topicoAberto.equals(topico)) {
            return;
        }
        JSONArray participantes = (JSONArray) json.get("participants");
        System.out.println("atualizando participantes na tela: " + participantes);
        modeloParticipante.clear();

        if (participantes == null || participantes.isEmpty()) {
            modeloParticipante.addElement("Nenhum participante.");
            return;
        }

        for (Object obj : participantes) {
            modeloParticipante.addElement(obj.toString());
        }
    }
    
    private void atulizarListaSolicitacoes(JSONObject json) {
        String topico = (String) json.get("topic");

        if (topicoAberto == null || !topicoAberto.equals(topico)) {
            return;
        }

        JSONArray solicitacoes = (JSONArray) json.get("requests");

        modeloSolicitacoes.clear();

        if (solicitacoes == null || solicitacoes.isEmpty()) {
            modeloSolicitacoes.addElement("Nenhuma solicitacao.");
            return;
        }

        for (Object obj : solicitacoes) {
            modeloSolicitacoes.addElement(obj.toString());
        }
    }
}
